//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://ws.esms.mobitel.lk/", ConfigurationName = "ServiceReference1.EnterpriseSMSWS")]
    public interface EnterpriseSMSWS
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.serviceTestResponse serviceTest(ServiceReference1.serviceTest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.serviceTestResponse> serviceTestAsync(ServiceReference1.serviceTest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.createSessionResponse createSession(ServiceReference1.createSession request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.createSessionResponse> createSessionAsync(ServiceReference1.createSession request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        ServiceReference1.renewSessionResponse renewSession(ServiceReference1.renewSession request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.renewSessionResponse> renewSessionAsync(ServiceReference1.renewSession request);

        // CODEGEN: Parameter 'session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        ServiceReference1.closeSessionResponse closeSession(ServiceReference1.closeSession request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.closeSessionResponse> closeSessionAsync(ServiceReference1.closeSession request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        ServiceReference1.isSessionResponse isSession(ServiceReference1.isSession request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.isSessionResponse> isSessionAsync(ServiceReference1.isSession request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.sendMessagesResponse sendMessages(ServiceReference1.sendMessages request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.sendMessagesResponse> sendMessagesAsync(ServiceReference1.sendMessages request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.sendMultipleMessagesResponse sendMultipleMessages(ServiceReference1.sendMultipleMessages request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.sendMultipleMessagesResponse> sendMultipleMessagesAsync(ServiceReference1.sendMultipleMessages request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.sendMessagesMultiLangResponse sendMessagesMultiLang(ServiceReference1.sendMessagesMultiLang request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.sendMessagesMultiLangResponse> sendMessagesMultiLangAsync(ServiceReference1.sendMessagesMultiLang request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.sendCampaignMessagesResponse sendCampaignMessages(ServiceReference1.sendCampaignMessages request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.sendCampaignMessagesResponse> sendCampaignMessagesAsync(ServiceReference1.sendCampaignMessages request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.getMessagesFromShortcodeResponse getMessagesFromShortcode(ServiceReference1.getMessagesFromShortcode request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.getMessagesFromShortcodeResponse> getMessagesFromShortcodeAsync(ServiceReference1.getMessagesFromShortcode request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.getMessagesFromLongNumberResponse getMessagesFromLongNumber(ServiceReference1.getMessagesFromLongNumber request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.getMessagesFromLongNumberResponse> getMessagesFromLongNumberAsync(ServiceReference1.getMessagesFromLongNumber request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.getSentMessageReportsResponse getSentMessageReports(ServiceReference1.getSentMessageReports request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.getSentMessageReportsResponse> getSentMessageReportsAsync(ServiceReference1.getSentMessageReports request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        ServiceReference1.getDeliveryReportsResponse getDeliveryReports(ServiceReference1.getDeliveryReports request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<ServiceReference1.getDeliveryReportsResponse> getDeliveryReportsAsync(ServiceReference1.getDeliveryReports request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class user
    {

        private long customerField;

        private bool customerFieldSpecified;

        private long idField;

        private bool idFieldSpecified;

        private string passwordField;

        private string usernameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerSpecified
        {
            get
            {
                return this.customerFieldSpecified;
            }
            set
            {
                this.customerFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class sentMessages
    {

        private string aliasField;

        private long idField;

        private bool idFieldSpecified;

        private string messageField;

        private string recipientField;

        private string statusField;

        private string timeSentField;

        private string timeDeliveredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string timeSent
        {
            get
            {
                return this.timeSentField;
            }
            set
            {
                this.timeSentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string timeDelivered
        {
            get
            {
                return this.timeDeliveredField;
            }
            set
            {
                this.timeDeliveredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class smsCampaignMessage
    {

        private string messageField;

        private long messageIdField;

        private string[] recipientsField;

        private int retriesField;

        private int esmClassField;

        private string senderField;

        private int sequenceNumField;

        private int statusField;

        private string timeField;

        private string typeField;

        private user userField;

        private int messageTypeField;

        private bool messageTypeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string[] recipients
        {
            get
            {
                return this.recipientsField;
            }
            set
            {
                this.recipientsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int retries
        {
            get
            {
                return this.retriesField;
            }
            set
            {
                this.retriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int esmClass
        {
            get
            {
                return this.esmClassField;
            }
            set
            {
                this.esmClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int sequenceNum
        {
            get
            {
                return this.sequenceNumField;
            }
            set
            {
                this.sequenceNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public user user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public int messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageTypeSpecified
        {
            get
            {
                return this.messageTypeFieldSpecified;
            }
            set
            {
                this.messageTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class smsMessageMultiLang
    {

        private string messageField;

        private long messageIdField;

        private string[] recipientsField;

        private int retriesField;

        private string senderField;

        private int sequenceNumField;

        private int statusField;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private string typeField;

        private user userField;

        private int messageTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string[] recipients
        {
            get
            {
                return this.recipientsField;
            }
            set
            {
                this.recipientsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int retries
        {
            get
            {
                return this.retriesField;
            }
            set
            {
                this.retriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int sequenceNum
        {
            get
            {
                return this.sequenceNumField;
            }
            set
            {
                this.sequenceNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public user user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public int messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class multipleSMS
    {

        private string messageField;

        private string recipientField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class smsMultipleMessage
    {

        private multipleSMS[] multipleSMSField;

        private string senderField;

        private int statusField;

        private bool statusFieldSpecified;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private int messageTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("multipleSMS", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public multipleSMS[] multipleSMS
        {
            get
            {
                return this.multipleSMSField;
            }
            set
            {
                this.multipleSMSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class smsMessage
    {

        private string messageField;

        private long messageIdField;

        private bool messageIdFieldSpecified;

        private string[] recipientsField;

        private int retriesField;

        private bool retriesFieldSpecified;

        private string senderField;

        private int sequenceNumField;

        private bool sequenceNumFieldSpecified;

        private int statusField;

        private bool statusFieldSpecified;

        private System.DateTime timeField;

        private bool timeFieldSpecified;

        private string typeField;

        private user userField;

        private int messageTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageIdSpecified
        {
            get
            {
                return this.messageIdFieldSpecified;
            }
            set
            {
                this.messageIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public string[] recipients
        {
            get
            {
                return this.recipientsField;
            }
            set
            {
                this.recipientsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int retries
        {
            get
            {
                return this.retriesField;
            }
            set
            {
                this.retriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retriesSpecified
        {
            get
            {
                return this.retriesFieldSpecified;
            }
            set
            {
                this.retriesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int sequenceNum
        {
            get
            {
                return this.sequenceNumField;
            }
            set
            {
                this.sequenceNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequenceNumSpecified
        {
            get
            {
                return this.sequenceNumFieldSpecified;
            }
            set
            {
                this.sequenceNumFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public user user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public int messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.esms.mobitel.lk/")]
    public partial class session
    {

        private System.DateTime expiryDateField;

        private bool expiryDateFieldSpecified;

        private long idField;

        private bool idFieldSpecified;

        private bool isActiveField;

        private bool isActiveFieldSpecified;

        private string sessionIdField;

        private long userField;

        private bool userFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime expiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified
        {
            get
            {
                return this.expiryDateFieldSpecified;
            }
            set
            {
                this.expiryDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public bool isActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isActiveSpecified
        {
            get
            {
                return this.isActiveFieldSpecified;
            }
            set
            {
                this.isActiveFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public long user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userSpecified
        {
            get
            {
                return this.userFieldSpecified;
            }
            set
            {
                this.userFieldSpecified = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "serviceTest", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class serviceTest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.user arg0;

        public serviceTest()
        {
        }

        public serviceTest(ServiceReference1.user arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "serviceTestResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class serviceTestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;

        public serviceTestResponse()
        {
        }

        public serviceTestResponse(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "createSession", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class createSession
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.user user;

        public createSession()
        {
        }

        public createSession(ServiceReference1.user user)
        {
            this.user = user;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "createSessionResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class createSessionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session @return;

        public createSessionResponse()
        {
        }

        public createSessionResponse(ServiceReference1.session @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "renewSession", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class renewSession
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        public renewSession()
        {
        }

        public renewSession(ServiceReference1.session session)
        {
            this.session = session;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "renewSessionResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class renewSessionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session @return;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;

        public renewSessionResponse()
        {
        }

        public renewSessionResponse(ServiceReference1.session @return, string status)
        {
            this.@return = @return;
            this.status = status;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "closeSession", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class closeSession
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        public closeSession()
        {
        }

        public closeSession(ServiceReference1.session session)
        {
            this.session = session;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "closeSessionResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class closeSessionResponse
    {

        public closeSessionResponse()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "isSession", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class isSession
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        public isSession()
        {
        }

        public isSession(ServiceReference1.session session)
        {
            this.session = session;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "isSessionResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class isSessionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;

        public isSessionResponse()
        {
        }

        public isSessionResponse(bool @return, string status)
        {
            this.@return = @return;
            this.status = status;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMessages", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMessages
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMessage smsMessage;

        public sendMessages()
        {
        }

        public sendMessages(ServiceReference1.session session, ServiceReference1.smsMessage smsMessage)
        {
            this.session = session;
            this.smsMessage = smsMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMessagesResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMessagesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;

        public sendMessagesResponse()
        {
        }

        public sendMessagesResponse(int @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMultipleMessages", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMultipleMessages
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMultipleMessage smsMultipleMessage;

        public sendMultipleMessages()
        {
        }

        public sendMultipleMessages(ServiceReference1.session session, ServiceReference1.smsMultipleMessage smsMultipleMessage)
        {
            this.session = session;
            this.smsMultipleMessage = smsMultipleMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMultipleMessagesResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMultipleMessagesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;

        public sendMultipleMessagesResponse()
        {
        }

        public sendMultipleMessagesResponse(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMessagesMultiLang", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMessagesMultiLang
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMessageMultiLang smsMessageMultiLang;

        public sendMessagesMultiLang()
        {
        }

        public sendMessagesMultiLang(ServiceReference1.session session, ServiceReference1.smsMessageMultiLang smsMessageMultiLang)
        {
            this.session = session;
            this.smsMessageMultiLang = smsMessageMultiLang;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendMessagesMultiLangResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendMessagesMultiLangResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;

        public sendMessagesMultiLangResponse()
        {
        }

        public sendMessagesMultiLangResponse(int @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendCampaignMessages", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendCampaignMessages
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsCampaignMessage smsCampaignMessage;

        public sendCampaignMessages()
        {
        }

        public sendCampaignMessages(ServiceReference1.session session, ServiceReference1.smsCampaignMessage smsCampaignMessage)
        {
            this.session = session;
            this.smsCampaignMessage = smsCampaignMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendCampaignMessagesResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class sendCampaignMessagesResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;

        public sendCampaignMessagesResponse()
        {
        }

        public sendCampaignMessagesResponse(int @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessagesFromShortcode", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getMessagesFromShortcode
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shortcode;

        public getMessagesFromShortcode()
        {
        }

        public getMessagesFromShortcode(ServiceReference1.session session, string shortcode)
        {
            this.session = session;
            this.shortcode = shortcode;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessagesFromShortcodeResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getMessagesFromShortcodeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMessage[] @return;

        public getMessagesFromShortcodeResponse()
        {
        }

        public getMessagesFromShortcodeResponse(ServiceReference1.smsMessage[] @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessagesFromLongNumber", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getMessagesFromLongNumber
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longNumber;

        public getMessagesFromLongNumber()
        {
        }

        public getMessagesFromLongNumber(ServiceReference1.session session, string longNumber)
        {
            this.session = session;
            this.longNumber = longNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessagesFromLongNumberResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getMessagesFromLongNumberResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMessage[] @return;

        public getMessagesFromLongNumberResponse()
        {
        }

        public getMessagesFromLongNumberResponse(ServiceReference1.smsMessage[] @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSentMessageReports", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getSentMessageReports
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;

        public getSentMessageReports()
        {
        }

        public getSentMessageReports(ServiceReference1.session session, string startDate, string endDate, string alias)
        {
            this.session = session;
            this.startDate = startDate;
            this.endDate = endDate;
            this.alias = alias;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSentMessageReportsResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getSentMessageReportsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.sentMessages[] @return;

        public getSentMessageReportsResponse()
        {
        }

        public getSentMessageReportsResponse(ServiceReference1.sentMessages[] @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getDeliveryReports", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getDeliveryReports
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.session session;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;

        public getDeliveryReports()
        {
        }

        public getDeliveryReports(ServiceReference1.session session, string alias)
        {
            this.session = session;
            this.alias = alias;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getDeliveryReportsResponse", WrapperNamespace = "https://ws.esms.mobitel.lk/", IsWrapped = true)]
    public partial class getDeliveryReportsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://ws.esms.mobitel.lk/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.smsMessage[] @return;

        public getDeliveryReportsResponse()
        {
        }

        public getDeliveryReportsResponse(ServiceReference1.smsMessage[] @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EnterpriseSMSWSChannel : ServiceReference1.EnterpriseSMSWS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EnterpriseSMSWSClient : System.ServiceModel.ClientBase<ServiceReference1.EnterpriseSMSWS>, ServiceReference1.EnterpriseSMSWS
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public EnterpriseSMSWSClient() :
                base(EnterpriseSMSWSClient.GetDefaultBinding(), EnterpriseSMSWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EnterpriseSMSImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EnterpriseSMSWSClient(EndpointConfiguration endpointConfiguration) :
                base(EnterpriseSMSWSClient.GetBindingForEndpoint(endpointConfiguration), EnterpriseSMSWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EnterpriseSMSWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(EnterpriseSMSWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EnterpriseSMSWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(EnterpriseSMSWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EnterpriseSMSWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.serviceTestResponse ServiceReference1.EnterpriseSMSWS.serviceTest(ServiceReference1.serviceTest request)
        {
            return base.Channel.serviceTest(request);
        }

        public string serviceTest(ServiceReference1.user arg0)
        {
            ServiceReference1.serviceTest inValue = new ServiceReference1.serviceTest();
            inValue.arg0 = arg0;
            ServiceReference1.serviceTestResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).serviceTest(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.serviceTestResponse> ServiceReference1.EnterpriseSMSWS.serviceTestAsync(ServiceReference1.serviceTest request)
        {
            return base.Channel.serviceTestAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.serviceTestResponse> serviceTestAsync(ServiceReference1.user arg0)
        {
            ServiceReference1.serviceTest inValue = new ServiceReference1.serviceTest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).serviceTestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.createSessionResponse ServiceReference1.EnterpriseSMSWS.createSession(ServiceReference1.createSession request)
        {
            return base.Channel.createSession(request);
        }

        public ServiceReference1.session createSession(ServiceReference1.user user)
        {
            ServiceReference1.createSession inValue = new ServiceReference1.createSession();
            inValue.user = user;
            ServiceReference1.createSessionResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).createSession(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createSessionResponse> ServiceReference1.EnterpriseSMSWS.createSessionAsync(ServiceReference1.createSession request)
        {
            return base.Channel.createSessionAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.createSessionResponse> createSessionAsync(ServiceReference1.user user)
        {
            ServiceReference1.createSession inValue = new ServiceReference1.createSession();
            inValue.user = user;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).createSessionAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.renewSessionResponse ServiceReference1.EnterpriseSMSWS.renewSession(ServiceReference1.renewSession request)
        {
            return base.Channel.renewSession(request);
        }

        public ServiceReference1.session renewSession(ServiceReference1.session session, out string status)
        {
            ServiceReference1.renewSession inValue = new ServiceReference1.renewSession();
            inValue.session = session;
            ServiceReference1.renewSessionResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).renewSession(inValue);
            status = retVal.status;
            return retVal.@return;
        }

        public System.Threading.Tasks.Task<ServiceReference1.renewSessionResponse> renewSessionAsync(ServiceReference1.renewSession request)
        {
            return base.Channel.renewSessionAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.closeSessionResponse ServiceReference1.EnterpriseSMSWS.closeSession(ServiceReference1.closeSession request)
        {
            return base.Channel.closeSession(request);
        }

        public void closeSession(ServiceReference1.session session)
        {
            ServiceReference1.closeSession inValue = new ServiceReference1.closeSession();
            inValue.session = session;
            ServiceReference1.closeSessionResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).closeSession(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.closeSessionResponse> ServiceReference1.EnterpriseSMSWS.closeSessionAsync(ServiceReference1.closeSession request)
        {
            return base.Channel.closeSessionAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.closeSessionResponse> closeSessionAsync(ServiceReference1.session session)
        {
            ServiceReference1.closeSession inValue = new ServiceReference1.closeSession();
            inValue.session = session;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).closeSessionAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.isSessionResponse ServiceReference1.EnterpriseSMSWS.isSession(ServiceReference1.isSession request)
        {
            return base.Channel.isSession(request);
        }

        public bool isSession(ServiceReference1.session session, out string status)
        {
            ServiceReference1.isSession inValue = new ServiceReference1.isSession();
            inValue.session = session;
            ServiceReference1.isSessionResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).isSession(inValue);
            status = retVal.status;
            return retVal.@return;
        }

        public System.Threading.Tasks.Task<ServiceReference1.isSessionResponse> isSessionAsync(ServiceReference1.isSession request)
        {
            return base.Channel.isSessionAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sendMessagesResponse ServiceReference1.EnterpriseSMSWS.sendMessages(ServiceReference1.sendMessages request)
        {
            return base.Channel.sendMessages(request);
        }

        public int sendMessages(ServiceReference1.session session, ServiceReference1.smsMessage smsMessage)
        {
            ServiceReference1.sendMessages inValue = new ServiceReference1.sendMessages();
            inValue.session = session;
            inValue.smsMessage = smsMessage;
            ServiceReference1.sendMessagesResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).sendMessages(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendMessagesResponse> ServiceReference1.EnterpriseSMSWS.sendMessagesAsync(ServiceReference1.sendMessages request)
        {
            return base.Channel.sendMessagesAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.sendMessagesResponse> sendMessagesAsync(ServiceReference1.session session, ServiceReference1.smsMessage smsMessage)
        {
            ServiceReference1.sendMessages inValue = new ServiceReference1.sendMessages();
            inValue.session = session;
            inValue.smsMessage = smsMessage;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sendMultipleMessagesResponse ServiceReference1.EnterpriseSMSWS.sendMultipleMessages(ServiceReference1.sendMultipleMessages request)
        {
            return base.Channel.sendMultipleMessages(request);
        }

        public string sendMultipleMessages(ServiceReference1.session session, ServiceReference1.smsMultipleMessage smsMultipleMessage)
        {
            ServiceReference1.sendMultipleMessages inValue = new ServiceReference1.sendMultipleMessages();
            inValue.session = session;
            inValue.smsMultipleMessage = smsMultipleMessage;
            ServiceReference1.sendMultipleMessagesResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).sendMultipleMessages(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendMultipleMessagesResponse> ServiceReference1.EnterpriseSMSWS.sendMultipleMessagesAsync(ServiceReference1.sendMultipleMessages request)
        {
            return base.Channel.sendMultipleMessagesAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.sendMultipleMessagesResponse> sendMultipleMessagesAsync(ServiceReference1.session session, ServiceReference1.smsMultipleMessage smsMultipleMessage)
        {
            ServiceReference1.sendMultipleMessages inValue = new ServiceReference1.sendMultipleMessages();
            inValue.session = session;
            inValue.smsMultipleMessage = smsMultipleMessage;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).sendMultipleMessagesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sendMessagesMultiLangResponse ServiceReference1.EnterpriseSMSWS.sendMessagesMultiLang(ServiceReference1.sendMessagesMultiLang request)
        {
            return base.Channel.sendMessagesMultiLang(request);
        }

        public int sendMessagesMultiLang(ServiceReference1.session session, ServiceReference1.smsMessageMultiLang smsMessageMultiLang)
        {
            ServiceReference1.sendMessagesMultiLang inValue = new ServiceReference1.sendMessagesMultiLang();
            inValue.session = session;
            inValue.smsMessageMultiLang = smsMessageMultiLang;
            ServiceReference1.sendMessagesMultiLangResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesMultiLang(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendMessagesMultiLangResponse> ServiceReference1.EnterpriseSMSWS.sendMessagesMultiLangAsync(ServiceReference1.sendMessagesMultiLang request)
        {
            return base.Channel.sendMessagesMultiLangAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.sendMessagesMultiLangResponse> sendMessagesMultiLangAsync(ServiceReference1.session session, ServiceReference1.smsMessageMultiLang smsMessageMultiLang)
        {
            ServiceReference1.sendMessagesMultiLang inValue = new ServiceReference1.sendMessagesMultiLang();
            inValue.session = session;
            inValue.smsMessageMultiLang = smsMessageMultiLang;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesMultiLangAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sendCampaignMessagesResponse ServiceReference1.EnterpriseSMSWS.sendCampaignMessages(ServiceReference1.sendCampaignMessages request)
        {
            return base.Channel.sendCampaignMessages(request);
        }

        public int sendCampaignMessages(ServiceReference1.session session, ServiceReference1.smsCampaignMessage smsCampaignMessage)
        {
            ServiceReference1.sendCampaignMessages inValue = new ServiceReference1.sendCampaignMessages();
            inValue.session = session;
            inValue.smsCampaignMessage = smsCampaignMessage;
            ServiceReference1.sendCampaignMessagesResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).sendCampaignMessages(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendCampaignMessagesResponse> ServiceReference1.EnterpriseSMSWS.sendCampaignMessagesAsync(ServiceReference1.sendCampaignMessages request)
        {
            return base.Channel.sendCampaignMessagesAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.sendCampaignMessagesResponse> sendCampaignMessagesAsync(ServiceReference1.session session, ServiceReference1.smsCampaignMessage smsCampaignMessage)
        {
            ServiceReference1.sendCampaignMessages inValue = new ServiceReference1.sendCampaignMessages();
            inValue.session = session;
            inValue.smsCampaignMessage = smsCampaignMessage;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).sendCampaignMessagesAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getMessagesFromShortcodeResponse ServiceReference1.EnterpriseSMSWS.getMessagesFromShortcode(ServiceReference1.getMessagesFromShortcode request)
        {
            return base.Channel.getMessagesFromShortcode(request);
        }

        public ServiceReference1.smsMessage[] getMessagesFromShortcode(ServiceReference1.session session, string shortcode)
        {
            ServiceReference1.getMessagesFromShortcode inValue = new ServiceReference1.getMessagesFromShortcode();
            inValue.session = session;
            inValue.shortcode = shortcode;
            ServiceReference1.getMessagesFromShortcodeResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromShortcode(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getMessagesFromShortcodeResponse> ServiceReference1.EnterpriseSMSWS.getMessagesFromShortcodeAsync(ServiceReference1.getMessagesFromShortcode request)
        {
            return base.Channel.getMessagesFromShortcodeAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.getMessagesFromShortcodeResponse> getMessagesFromShortcodeAsync(ServiceReference1.session session, string shortcode)
        {
            ServiceReference1.getMessagesFromShortcode inValue = new ServiceReference1.getMessagesFromShortcode();
            inValue.session = session;
            inValue.shortcode = shortcode;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromShortcodeAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getMessagesFromLongNumberResponse ServiceReference1.EnterpriseSMSWS.getMessagesFromLongNumber(ServiceReference1.getMessagesFromLongNumber request)
        {
            return base.Channel.getMessagesFromLongNumber(request);
        }

        public ServiceReference1.smsMessage[] getMessagesFromLongNumber(ServiceReference1.session session, string longNumber)
        {
            ServiceReference1.getMessagesFromLongNumber inValue = new ServiceReference1.getMessagesFromLongNumber();
            inValue.session = session;
            inValue.longNumber = longNumber;
            ServiceReference1.getMessagesFromLongNumberResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromLongNumber(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getMessagesFromLongNumberResponse> ServiceReference1.EnterpriseSMSWS.getMessagesFromLongNumberAsync(ServiceReference1.getMessagesFromLongNumber request)
        {
            return base.Channel.getMessagesFromLongNumberAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.getMessagesFromLongNumberResponse> getMessagesFromLongNumberAsync(ServiceReference1.session session, string longNumber)
        {
            ServiceReference1.getMessagesFromLongNumber inValue = new ServiceReference1.getMessagesFromLongNumber();
            inValue.session = session;
            inValue.longNumber = longNumber;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromLongNumberAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getSentMessageReportsResponse ServiceReference1.EnterpriseSMSWS.getSentMessageReports(ServiceReference1.getSentMessageReports request)
        {
            return base.Channel.getSentMessageReports(request);
        }

        public ServiceReference1.sentMessages[] getSentMessageReports(ServiceReference1.session session, string startDate, string endDate, string alias)
        {
            ServiceReference1.getSentMessageReports inValue = new ServiceReference1.getSentMessageReports();
            inValue.session = session;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.alias = alias;
            ServiceReference1.getSentMessageReportsResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).getSentMessageReports(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getSentMessageReportsResponse> ServiceReference1.EnterpriseSMSWS.getSentMessageReportsAsync(ServiceReference1.getSentMessageReports request)
        {
            return base.Channel.getSentMessageReportsAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.getSentMessageReportsResponse> getSentMessageReportsAsync(ServiceReference1.session session, string startDate, string endDate, string alias)
        {
            ServiceReference1.getSentMessageReports inValue = new ServiceReference1.getSentMessageReports();
            inValue.session = session;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.alias = alias;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).getSentMessageReportsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getDeliveryReportsResponse ServiceReference1.EnterpriseSMSWS.getDeliveryReports(ServiceReference1.getDeliveryReports request)
        {
            return base.Channel.getDeliveryReports(request);
        }

        public ServiceReference1.smsMessage[] getDeliveryReports(ServiceReference1.session session, string alias)
        {
            ServiceReference1.getDeliveryReports inValue = new ServiceReference1.getDeliveryReports();
            inValue.session = session;
            inValue.alias = alias;
            ServiceReference1.getDeliveryReportsResponse retVal = ((ServiceReference1.EnterpriseSMSWS)(this)).getDeliveryReports(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getDeliveryReportsResponse> ServiceReference1.EnterpriseSMSWS.getDeliveryReportsAsync(ServiceReference1.getDeliveryReports request)
        {
            return base.Channel.getDeliveryReportsAsync(request);
        }

        public System.Threading.Tasks.Task<ServiceReference1.getDeliveryReportsResponse> getDeliveryReportsAsync(ServiceReference1.session session, string alias)
        {
            ServiceReference1.getDeliveryReports inValue = new ServiceReference1.getDeliveryReports();
            inValue.session = session;
            inValue.alias = alias;
            return ((ServiceReference1.EnterpriseSMSWS)(this)).getDeliveryReportsAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EnterpriseSMSImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EnterpriseSMSImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://msmsenterpriseapi.mobitel.lk/mSMSEnterpriseAPI/mSMSEnterpriseAPI.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EnterpriseSMSWSClient.GetBindingForEndpoint(EndpointConfiguration.EnterpriseSMSImplPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EnterpriseSMSWSClient.GetEndpointAddress(EndpointConfiguration.EnterpriseSMSImplPort);
        }

        public enum EndpointConfiguration
        {

            EnterpriseSMSImplPort,
        }
    }
}
